"""
Configuration constants for the Adaptive RL Edge Scheduler project.
"""

NUM_NODES = 5
MAX_CAPACITY = 10

TASK_SIZE_MIN = 1
TASK_SIZE_MAX = 3

NORMAL_ARRIVAL_PROB = 0.7
BURST_ARRIVAL_PROB = 0.95
BURST_WINDOW_START = 200
BURST_WINDOW_END = 300

TOTAL_TIMESTEPS = 1000

# Base metrics
BASE_LATENCY = 1
LATENCY_ALPHA = 0.5
OVERLOAD_THRESHOLD = 10
LOAD_DECREASE_RATE = 1

# RL Specifics
PENALTY_OVERLOAD = -10
LOAD_VARIANCE_WEIGHT = 0.3

RANDOM_SEED = 42
